<a href="https://colab.research.google.com/github/Rabiah86/PyTorch-Crash-course/blob/main/PyTorch_Tutorial_2D_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:

import numpy as np 
import matplotlib.pyplot as plt
import torch
import pandas as pd
# from 1D to 2D
OneD = torch.tensor([4,5,7])
OneD.view(-1,1) # -1 means automatically infer the number of rows
#if you try OneD.view(-1,2) then you'll get an error



tensor([[4],
        [5],
        [7]])

In [13]:
#OR can be a list
TwoD= [1,2,3],[4,5,6],[7,8,9]
TensorTwoDtorch= torch.tensor(TwoD)
print("The dimension of twoD_tensor: ",TensorTwoDtorch.ndimension())
print("The shape of twoD_tensor: ", TensorTwoDtorch.shape)
print("The shape of twoD_tensor: ", TensorTwoDtorch.size())
print("The number of elements in twoD_tensor: ", TensorTwoDtorch.numel() )


The dimension of twoD_tensor:  2
The shape of twoD_tensor:  torch.Size([3, 3])
The shape of twoD_tensor:  torch.Size([3, 3])
The number of elements in twoD_tensor:  9


In [17]:
#to numpy and then back to a tensor
Num = TensorTwoDtorch.numpy()
Back= torch.from_numpy(Num)
print('original tensor ', TensorTwoDtorch )
print('Numpy ',Num)
print('Tensor from Numpy ', Back)
#################
TensorTwoDtorch[1][1]=100
print('after modifying the original tensor')
print('original tensor ', TensorTwoDtorch )
print('Numpy ',Num)
print('Tensor from Numpy ', Back)
### have you noticed that they all got updated

original tensor  tensor([[  1,   2,   3],
        [  4, 100,   6],
        [  7,   8,   9]])
Numpy  [[  1   2   3]
 [  4 100   6]
 [  7   8   9]]
Tensor from Numpy  tensor([[  1,   2,   3],
        [  4, 100,   6],
        [  7,   8,   9]])
after modifying the original tensor
original tensor  tensor([[  1,   2,   3],
        [  4, 100,   6],
        [  7,   8,   9]])
Numpy  [[  1   2   3]
 [  4 100   6]
 [  7   8   9]]
Tensor from Numpy  tensor([[  1,   2,   3],
        [  4, 100,   6],
        [  7,   8,   9]])


In [30]:
#panda series are one D of any type
#dataframes are any dimension 
df = pd.DataFrame({'a':[11,21,31],'b':[12,22,312]}) #remember that a and b are columns where in tensors each is a row
print(df.b)
print(df.values)
new_tensor=torch.tensor(df.values)
print(new_tensor)
print(df.values.dtype)
new_tensor.dtype

0     12
1     22
2    312
Name: b, dtype: int64
[[ 11  12]
 [ 21  22]
 [ 31 312]]
tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])
int64


torch.int64

In [ ]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

In [35]:
####Slicing 
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 1st-row first two columns? ", tensor_example[0:2, 0:2]) #row 0 and column 0 and 1
print("What is the value on 1st-row first two columns? ", tensor_example[0][0:2])
b=tensor_example[0][0:2]
b.ndimension() #dimension is different than size/shape


What is the value on 1st-row first two columns?  tensor([[11, 12],
        [21, 22]])
What is the value on 1st-row first two columns?  tensor([11, 12])


1