<a href="https://colab.research.google.com/github/Rabiah86/PyTorch-Crash-course/blob/main/Pytorch_Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch
from torch.utils.data import Dataset
torch.manual_seed(1)


In [15]:
class toy_set(Dataset):
  def __init__(self,length=100,transform=None):
     self.len= length
     self.transform = transform
     self.x=2*torch.ones(length,2) #2 is the size of each item, single iem, tuple , etc
     self.y=torch.ones(length)
  def __getitem__(self, index):
    sample= self.x[index],self.y[index]
    if self.transform != None:
      self.transform(sample)
    return sample

  def __len__(self):
    return self.len
     

In [16]:
mydata= toy_set()
print(mydata.len) # .attribute 
print(mydata)
print(mydata[0])

100
(tensor([2., 2.]), tensor(1.))


In [ ]:
for x,y in mydata:
  print(x,y)

In [27]:
class add_mult(object):
  def __init__(self, addx = 1,muly =2 ):
    self.addx=addx
    self.muly=muly
  def __call__(self,sample):
    x= sample[0]
    y=sample[1]
    return x+self.addx, y*self.muly


In [41]:
trans= add_mult()
newdataset= toy_set(transform=trans)
newdataset[1]
#or you can transform an existing dataset 
trans2=add_mult()
x,y= mydata[0]
x_,y_= trans2(mydata[0])
###########Important########
print(x_,y_)
print(x,y)

tensor([3., 3.]) tensor(2.)
tensor([2., 2.]) tensor(1.)
